import './globals.css'
import Link from 'next/link'
import { Control } from './Control'

export const metadata = {
  title: 'Web Tutorial',
  description: 'Generated by Solomon Kim',
}

export default async function RootLayout({ children }) {
  const resp = await fetch(process.env.NEXT_PUBLIC_API_URL+'topics',{ cache: 'no-store' } )
  const topics = await resp.json()

  return (
    <html lang="en">
      <body>
        <h1>
          <Link href="/">WEB</Link>
          <ol>
            {topics.map((topic) => {
              return (
                <li key={topic.id}>
                  <Link href={`/read/${topic.id}`}>
                    {topic.title}
                  </Link>
                </li>
              )
            })}
          </ol>
        </h1>
        {children}
        <Control/>
      </body>
    </html>
  )
}

